# Variants
[simple.v-turn-v-straight]
tag = "cv73"
sampler = 'AΛΔ'
description = 'Standard, straight `A`, `Λ`, `Δ`'
A = "straight"
Lambda = "straight"
Delta = "straight"

[simple.v-turn-v-curly]
tag = "cv74"
sampler = 'AΛΔ'
description = 'Slightly curly `A`, `Λ`, `Δ`, like Iosevka 2.x'
A = "curly"
Lambda = "curly"
Delta = "curly"

[simple.v-capital-g-tooth]
tag = "cv91"
sampler = "G"
description = "Toothed G"
G = "toothed"

[simple.v-capital-g-toothless]
tag = "cv92"
sampler = "G"
description = "Toothless G"
G = "toothless"

[simple.v-capital-q-taily]
tag = 'cv42'
sampler = 'Q'
description = '`Q` with a curly tail'
Q = 'taily'

[simple.v-capital-q-straight]
tag = 'cv43'
sampler = 'Q'
description = '`Q` with a straight tail like in the old versions'
Q = 'straight'

[simple.v-capital-r-straight]
tag = "cv82"
sampler = 'R'
description = 'Standard, straight-leg `R`'
R = "straight"

[simple.v-capital-r-curly]
tag = "cv83"
sampler = 'R'
description = ' Slightly curly-legged `R`, like Iosevka 2.x'
R = "curly"

[simple.v-capital-y-straight]
tag = "cv80"
sampler = 'Y'
description = 'Standard, straight `Y`'
Y = "straight"

[simple.v-capital-y-curly]
tag = "cv81"
sampler = 'Y'
description = 'Slightly curly `Y`, like Iosevka 2.x'
Y = "curly"

[simple.v-a-singlestorey]
tag = 'cv02'
sampler = 'a'
description = 'Single-storey `a`'
a = 'singlestorey'

[simple.v-a-doublestorey]
tag = 'cv01'
sampler = 'a'
description = 'Double-storey `a`'
a = 'doublestorey'

[simple.v-f-straight]
tag = "cv52"
sampler = 'f'
description = '`f` without bottom hook'
f = "straight"

[simple.v-f-tailed]
tag = "cv53"
sampler = 'f'
description = '`f` with a leftward bottom hook'
f = "tailed"

[simple.v-f-serifed]
tag = "cv84"
sampler = 'f'
description = '`f` with bottom serif'
f = "serifed"

[simple.v-g-singlestorey]
tag = 'cv12'
sampler = 'g'
description = 'Single-storey `g`'
g = 'singlestorey'

[simple.v-g-doublestorey]
tag = 'cv11'
sampler = 'g'
description = 'Double-storey `g`'
g = 'doublestorey'

[simple.v-g-opendoublestorey]
tag = 'cv24'
sampler = 'g'
description = 'Open Double-storey `g`, like Trebuchet MS or Fira Code'
g = 'opendoublestorey'

[simple.v-i-serifed]
tag = 'cv03'
sampler = 'i'
description = 'Serifed `i`'
dotlessi = 'serifed'

[simple.v-i-italic]
tag = 'cv04'
sampler = 'i'
description = 'Italic `i`'
dotlessi = 'italic'

[simple.v-i-hooky]
tag = 'cv05'
sampler = 'i'
description = 'Hooky `i`'
dotlessi = 'hooky'

[simple.v-i-line]
tag = "cv56"
sampler = 'i'
description = '`i` like a straight line'
dotlessi = "line"

[simple.v-i-zshaped]
tag = 'cv06'
sampler = 'i'
description = 'Z-shaped `i`'
dotlessi = 'zshaped'

[simple.v-i-tailed]
tag = "cv88"
sampler = 'i'
description = "Tailed `i`"
dotlessi = 'tailed'

[simple.v-j-line]
tag = "cv57"
sampler = 'j'
description = '`j` like a straight line'
dotlessj = "line"

[simple.v-j-serifed]
tag = "cv58"
sampler = 'j'
description = '`j` with top serif'
dotlessj = "serifed"

[simple.v-l-hooky]
tag = 'cv09'
sampler = 'l'
description = 'Hooky `l`'
l = 'hooky'

[simple.v-l-zshaped]
tag = 'cv10'
sampler = 'l'
description = 'Z-shaped `i`'
l = 'zshaped'

[simple.v-l-serifed]
tag = 'cv07'
sampler = 'l'
description = 'Serifed `l`'
l = 'serifed'

[simple.v-l-italic]
tag = 'cv08'
sampler = 'l'
description = 'Italic, cursive `l`'
l = 'italic'

[simple.v-l-line]
tag = "cv59"
sampler = 'l'
description = '`l` like a straight line'
l = "line"

[simple.v-l-tailed]
tag = 'cv27'
sampler = 'l'
description = '`l` with a curved tail'
l = 'tailed'

[simple.v-l-hookybottom]
tag = 'cv28'
sampler = 'l'
description = '`l` with a straight tail'
l = 'hookybottom'

[simple.v-k-straight]
tag = "cv68"
sampler = 'kK'
description = '`k` with standard shape'
k = 'straight'
K = 'straight'

[simple.v-k-curly]
tag = "cv69"
sampler = 'kK'
description = 'Slightly curly `k`, like Iosevka 2.x'
k = 'curly'
K = 'curly'

[simple.v-k-cursive]
tagItalic = "cv70"
sampler = 'kK'
description = '`k` with a cursive loop'
k = 'cursive'
K = 'straight'

[simple.v-m-normal]
tag = 'cv25'
sampler = 'm'
description = '`m` with normal middle leg, touching the baseline'
m = 'normal'

[simple.v-m-shortleg]
tag = 'cv26'
sampler = 'm'
description = '`m` with shorter middle leg, like Ubuntu Mono'
m = 'shortleg'

[simple.v-r-straight]
tag = "cv85"
sampler = 'r'
description = 'Straight, serif-less `r`'
r = "straight"

[simple.v-r-serifed]
tag = "cv86"
sampler = 'r'
description = '`r` with serif at both top and bottom'
r = "serifed"

[simple.v-r-top-serifed]
tag = "cv87"
sampler = 'r'
description = '`r` with serifs at top-left only'
r = "top-serifed"

[simple.v-t-standard]
tag = 'cv40'
sampler = 't'
description = 'Standard `t` shape'
t = 'standard'

[simple.v-t-cross]
tag = 'cv41'
sampler = 't'
description = 'Futura-like `t` shape'
t = 'cross'

[simple.v-u-with-bar]
tag = "cv89"
sampler = "u"
description = "Normal `u` with right bar"
u = "withBar"

[simple.v-u-without-bar]
tag = "cv90"
sampler = "u"
description = "Normal `u` without right bar, like a smaller uppercase `U`"
u = "withoutBar"

[simple.v-v-straight]
tag = "cv71"
sampler = 'vV'
description = 'Standard, straight `V` and `v`'
v = "straight"
V = "straight"

[simple.v-v-curly]
tag = "cv72"
sampler = 'vV'
description = ' Slightly curly `V` and `v`, like Iosevka 2.x'
v = "curly"
V = "curly"

[simple.v-w-straight]
tag = "cv75"
sampler = 'wW'
description = 'Standard, straight `W` and `w`'
W = "straight"
w = "straight"

[simple.v-w-curly]
tag = "cv76"
sampler = 'wW'
description = 'Slightly curly `W` and `w`, like Iosevka 2.x'
W = "curly"
w = "curly"

[simple.v-x-straight]
tag = "cv77"
sampler = 'xX'
description = 'Standard, straight `X` and `x`'
X = "straight"
x = "straight"

[simple.v-x-curly]
tag = "cv78"
sampler = 'xX'
description = 'Slightly curly `X` and `x`, like Iosevka 2.x'
X = "curly"
x = "curly"

[simple.v-y-straight]
tag = "cv48"
sampler = 'y'
description = 'More-straight letter `y`'
y = "straight"
cyrU = "straight"

[simple.v-y-curly]
tag = "cv79"
sampler = 'y'
description = 'More curly letter `y`, like Iosevka 2.x'
y = "curly"
cyrU = "curly"

[simple.v-y-cursive]
tag = "cv49"
sampler = 'y'
description = 'Cursive-like `y`'
y = "cursive"
cyrU = "straight"

[simple.v-eszet-traditional]
tag = 'cv34'
sampler = 'ß'
description = 'Traditional, Fraktur-like Eszet'
eszet = 'traditional'

[simple.v-eszet-sulzbacher]
tag = 'cv35'
sampler = 'ß'
description = 'A more modern, beta-like Eszet'
eszet = 'sulzbacher'

[simple.v-lambda-straight]
tag = "cv94"
sampler = 'λ'
description = 'More-straight letter `λ`'
lambda = "straight"

[simple.v-lambda-curly]
tag = "cv95"
sampler = 'λ'
description = 'More curly letter `λ`, like Iosevka 2.x'
lambda = "curly"

[simple.v-zero-slashed]
tag = 'cv13'
sampler = '0'
description = 'Slashed Zero `0`'
zero = 'slashed'

[simple.v-zero-dotted]
tag = 'cv14'
sampler = '0'
description = 'Dotted Zero `0`'
zero = 'dotted'

[simple.v-zero-unslashed]
tag = 'cv15'
sampler = '0'
description = 'O-like `0`'
zero = 'unslashed'

[simple.v-zero-reverse-slashed]
tag = 'cv93'
sampler = '0'
description = 'Reverse-slashed `0`'
zero = 'reverse-slashed'

[simple.v-one-nobase]
tag = "cv50"
sampler = '1'
description = '`1` with bottom serif'
one = "nobase"

[simple.v-one-base]
tag = "cv51"
sampler = '1'
description = '`1` without bottom serif'
one = "base"

[simple.v-three-flattop]
tag = 'cv46'
sampler = '3'
description = 'Flat top `3` (Like Museo Sans / Montserrat)'
three = 'flattop'

[simple.v-three-twoarcs]
tag = 'cv47'
sampler = '3'
description = 'Arched top `3`'
three = 'twoarcs'

[simple.v-seven-noserif]
tag = "cv64"
sampler = '7'
description = '`7` without serif'
seven = "noserif"

[simple.v-seven-serifed]
tag = "cv65"
sampler = '7'
description = '`7` with initial serif'
seven = "serifed"

[simple.v-nine-closed-contour]
tag = "cv96"
sampler = '9'
description = '`9` with a more closed'
nine = "closedContour"

[simple.v-nine-turned-six]
tag = "cv97"
sampler = '9'
description = '`9` with a more open contour like a turned `6`'
nine = "turnedSix"

[simple.v-tilde-high]
tag = 'cv16'
sampler = '~'
description = 'Higher tilde `~`'
asciitilde = 'high'

[simple.v-tilde-low]
tag = 'cv17'
sampler = '~'
description = 'Lower tilde `~`'
asciitilde = 'low'

[simple.v-asterisk-high]
tag = 'cv18'
sampler = '*'
description = 'Higher five-pointed asterisk `*`'
asterisk = 'high'

[simple.v-asterisk-low]
tag = 'cv19'
sampler = '*'
description = 'Lower five-pointed asterisk `*`'
asterisk = 'low'

[simple.v-asterisk-hexhigh]
tag = "cv60"
sampler = "*"
description = 'Higher six-pointed asterisk `*`'
asterisk = "hexhigh"

[simple.v-asterisk-hexlow]
tag = "cv61"
sampler = "*"
description = 'Lower six-pointed asterisk `*`'
asterisk = "hexlow"

[simple.v-underscore-high]
tag = 'cv20'
sampler = '_'
description = 'Higher underscore `_`, at baseline'
underscore = 'high'

[simple.v-underscore-low]
tag = 'cv21'
sampler = '_'
description = 'Lower underscore `_`, below baseline'
underscore = 'low'

[simple.v-paragraph-high]
tag = 'cv22'
sampler = '¶'
description = 'Higher paragraph symbol `¶`'
paragraph = 'high'
revertParagraph = 'high'

[simple.v-paragraph-low]
tag = 'cv23'
sampler = '¶'
description = 'Lower paragraph symbol `¶`'
paragraph = 'low'
revertParagraph = 'low'

[simple.v-caret-high]
tag = 'cv29'
sampler = '^'
description = 'Higher circumflex `^`'
asciicaret = 'high'

[simple.v-caret-low]
tag = 'cv30'
sampler = '^'
description = 'Lower circumflex `^`'
asciicaret = 'low'

[simple.v-brace-straight]
tag = 'cv36'
sampler = '{ }'
description = 'More straight braces'
braceLeft = 'straight'
braceRight = 'straight'

[simple.v-brace-curly]
tag = 'cv37'
sampler = '{ }'
description = 'More curly braces'
braceLeft = 'curly'
braceRight = 'curly'

[simple.v-numbersign-upright]
tag = 'cv44'
sampler = '#'
description = 'Number sign with vertical bars'
numbersign = 'upright'

[simple.v-numbersign-slanted]
tag = 'cv45'
sampler = '#'
description = 'Number sign with slanted bars'
numbersign = 'slanted'


[simple.v-at-threefold]
tag = 'cv31'
sampler = '@'
description = 'The long, three-fold At symbol (`@`)'
at = 'threefold'

[simple.v-at-fourfold]
tag = 'cv32'
sampler = '@'
description = 'The traditional, four-fold At symbol (`@`)'
at = 'fourfold'

[simple.v-at-short]
tag = 'cv33'
sampler = '@'
description = 'The shorter, Fira-like At symbol (`@`)'
at = 'short'

[simple.v-dollar-open]
tag = 'cv38'
sampler = '$'
description = 'Dollar symbol with open contour'
dollar = 'open'

[simple.v-dollar-through]
tag = 'cv39'
sampler = '$'
description = 'Dollar symbol with strike-through vertical bar'
dollar = 'through'

[simple.v-dollar-opencap]
tag = "cv54"
sampler = '$'
description = 'Dollar symbol with open contour, not exceeding baseline and ascender'
dollar = "opencap"

[simple.v-dollar-throughcap]
tag = "cv55"
sampler = '$'
description = 'Dollar symbol with strike-through vertical bar, not exceeding baseline and ascender'
dollar = "throughcap"

[simple.v-percent-dots]
tag = "cv62"
sampler = '%'
description = 'Percent `%`, Per-mille `‰` and basis point `‱` using rectangular dots'
percent = "dots"

[simple.v-percent-rings]
tag = "cv63"
sampler = '%'
description = 'Percent `%`, Per-mille `‰` and basis point `‱` using rings'
percent = "rings"

[simple.v-lig-ltgteq-flat]
tag = "cv66"
sampler = '<= >='
description = 'The lower bar of `<=` and `>=` ligation is flat'
"eq.at-lteq.lig2" = "flat"
"eq.at-gteq.lig2" = "flat"

[simple.v-lig-ltgteq-slanted]
tag = "cv67"
sampler = '<= >='
description = 'The lower bar of `<=` and `>=` ligation is slanted'
"eq.at-lteq.lig2" = "slanted"
"eq.at-gteq.lig2" = "slanted"

########## "Untagged" variants, used for Aile, etc.

[simple.v-capital-i-straight]
I = "line" # set on purpose to use II diversity

[simple.v-capital-i-serifed]
I = "serifed"

[simple.v-capital-j-straight]
J = "straight"

[simple.v-capital-j-serifed]
J = 'serifed'

[simple.v-f-narrow]
f = 'narrow'

[simple.v-t-narrow]
t = 'narrow'

[simple.v-j-narrow]
dotlessj = "narrow"

[simple.v-j-narrow-serifed]
dotlessj = "narrow-serifed"

[simple.v-r-narrow]
r = "narrow"

[default]
design = [
	'v-m-normal',
	'v-t-standard',
	'v-capital-q-taily',
	'v-zero-slashed',
	'v-tilde-low',
	'v-asterisk-high',
	'v-paragraph-high',
	'v-caret-high',
	'v-underscore-high',
	'v-at-threefold',
	'v-eszet-sulzbacher',
	'v-brace-curly',
	'v-dollar-through',
	'v-numbersign-upright',
	'v-three-twoarcs',
	'v-one-nobase',
	'v-percent-rings',
	'v-g-singlestorey',
	'v-capital-i-serifed',
	'v-capital-j-serifed',
	'v-r-straight',
	'v-seven-noserif',
	'others',
	'v-lig-ltgteq-flat',
	'v-v-straight',
	'v-turn-v-straight',
	'v-w-straight',
	'v-x-straight',
	'v-capital-y-straight',
	'v-capital-r-straight',
	'v-u-with-bar',
	'v-capital-g-tooth',
	'v-lambda-straight',
	'v-nine-closed-contour'
]
upright = [
	'v-a-doublestorey',
	'v-i-serifed',
	'v-j-serifed',
	'v-l-serifed',
	'v-y-straight',
	'v-f-straight',
	'v-k-straight'
]
italic = [
	'v-a-singlestorey',
	'v-i-italic',
	'v-j-serifed',
	'v-l-italic',
	'v-y-cursive',
	'v-f-tailed',
	'v-k-cursive'
]

[composite.slab]
design = ['v-one-base', 'v-seven-serifed']
upright = ['v-f-serifed', 'v-r-serifed']
italic =  ['v-f-tailed', 'v-r-top-serifed']

# Composite character options, overrides default settings above.
[composite.ss01]
description = "Andale Mono Style"
design = ['v-i-hooky', 'v-a-doublestorey', 'v-g-doublestorey', 'v-l-zshaped', 'v-at-fourfold', 'v-zero-dotted', 'v-g-doublestorey', 'v-brace-straight', 'v-underscore-low', 'v-numbersign-slanted', 'v-asterisk-hexhigh']

[composite.ss02]
description = "Anonymous Pro Style"
design = ['v-at-fourfold', 'v-a-doublestorey', 'v-brace-straight', 'v-l-serifed', 'v-i-serifed', 'v-asterisk-hexlow']

[composite.ss03]
description = 'Consolas Style'
design = ['v-at-fourfold', 'v-underscore-low', 'v-brace-straight', 'v-numbersign-slanted', 'v-asterisk-hexhigh']
upright = ['v-g-doublestorey']
italic = ['v-g-singlestorey']

[composite.ss04]
description = 'Menlo Style'
design = ['v-at-threefold', 'v-a-doublestorey', 'v-underscore-low', 'v-i-serifed', 'v-l-italic', 'v-brace-straight', 'v-numbersign-slanted', 'v-asterisk-hexlow']

[composite.ss05]
description = 'Fira Mono Style'
design = ['v-at-short', 'v-underscore-low', 'v-a-doublestorey', 'v-i-serifed', 'v-g-opendoublestorey', 'v-l-italic', 'v-numbersign-slanted', 'v-zero-dotted',]

[composite.ss06]
description = 'Liberation Mono Style'
design = ['v-at-fourfold', 'v-a-doublestorey', 'v-i-serifed', 'v-l-serifed', 'v-brace-straight', 'v-zero-dotted', 'v-numbersign-slanted']

[composite.ss07]
description = 'Monaco Style'
design = ['v-at-fourfold', 'v-a-singlestorey', 'v-i-zshaped', 'v-l-zshaped', 'v-brace-straight', 'v-numbersign-slanted', 'v-asterisk-hexhigh']

[composite.ss08]
description = 'Pragmata Pro Style'
design = ['v-at-threefold', 'v-a-doublestorey', 'v-l-serifed', 'v-i-serifed', 'v-asterisk-low', 'v-zero-dotted', 'v-brace-straight', 'v-dollar-open', 'v-underscore-low', 'v-numbersign-slanted', 'v-percent-dots', 'v-v-curly', 'v-turn-v-curly', 'v-w-curly', 'v-x-curly', 'v-capital-y-curly', 'v-capital-r-curly', 'v-k-curly', 'v-y-curly', 'v-lambda-curly']
upright = ['v-g-doublestorey']
italic  = ['v-g-singlestorey']

[composite.ss09]
description = 'Source Code Pro Style'
design = ['v-at-threefold', 'v-l-italic', 'v-asterisk-low', 'v-zero-dotted', 'v-dollar-open', 'v-numbersign-slanted']
upright = ['v-i-hooky', 'v-g-doublestorey']
italic = ['v-g-singlestorey']

[composite.ss10]
description = 'Envy Code R Style'
design = ['v-at-threefold', 'v-a-doublestorey', 'v-underscore-low', 'v-i-hooky', 'v-l-hooky', 'v-asterisk-low']

[composite.ss11]
description = 'X Window Style'
design = ['v-zero-unslashed', 'v-tilde-high', 'v-brace-straight', 'v-dollar-through', 'v-three-flattop', 'v-at-threefold']

[composite.ss12]
description = 'Ubuntu Mono Style'
design = ['v-at-threefold', 'v-a-doublestorey', 'v-f-straight', 'v-underscore-low', 'v-i-italic', 'v-l-italic', 'v-m-shortleg', 'v-y-straight', 'v-brace-straight', 'v-zero-dotted', 'v-one-base-serif', 'v-numbersign-slanted']

[composite.ss13]
description = 'Lucida Style'
design = ['v-i-hooky', 'v-l-hooky', 'v-zero-dotted', 'v-underscore-low', 'v-caret-low', 'v-numbersign-slanted', 'v-one-base']

[composite.ss14]
description = 'JetBrains Mono Style'
design = ['v-i-serifed', 'v-l-italic', 'v-u-without-bar', 'v-zero-dotted', 'v-three-flattop', 'v-capital-q-straight', 'v-asterisk-low']

[composite.ss20]
description = 'Curly Style'
design = ['v-v-curly', 'v-turn-v-curly', 'v-w-curly', 'v-x-curly', 'v-capital-y-curly', 'v-capital-r-curly', 'v-lambda-curly']
upright = ['v-k-curly', 'v-y-curly']
italic  = ['v-k-cursive', 'v-y-cursive']
